spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_pms
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: bearsof
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 12000